language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "iojs"
env:
- SASS_VERSION=3.3.14
- SASS_VERSION=latest
before_script:
- if test $SASS_VERSION != "latest"; then gem install sass -v $SASS_VERSION; else gem install sass; fi
script: npm test
matrix:
  fast_finish: true
  allow_failures:
    - node_js: "0.11"
    - node_js: "iojs"
